---
name: 'Build Dev'

# yamllint disable-line rule:truthy
on:
  #   push:
  #     branches: [ master ]
  #     paths:
  #       - "youtube-dl/**"
  workflow_dispatch:

jobs:
  version:
    name: Generate version
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Set version
        id: version
        run: |
          version=$(date --utc '+%Y-%m-%d-%H-%M')
          echo "Version: ${version}"
          echo "::set-output name=version::${version}"

  build:
    name: Build dev and push to Docker
    needs: version
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo Version: ${{ needs.version.outputs.version }}
      - uses: actions/checkout@v2.3.4
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: home-assistant/builder@master
        with:
          args: |
            --no-latest \
            --all \
            --target "/data/youtube-dl" \
            --docker-hub ${{ secrets.DOCKERHUB_USERNAME }} \
            --image youtube-dl-{arch} \
            --version ${{ needs.version.outputs.version }}

  repository:
    name: Update Dev repository
    needs:
      - version
      - build
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo Version: ${{ needs.version.outputs.version }}
      - uses: actions/checkout@v2.3.4
        with:
          repository: einschmidt/hassio-addons-dev
          token: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Update json
        run: |
          cd youtube-dl
          jq '.version |= "${{ needs.version.outputs.version }}"' config.json > tmp.$$.json
          mv tmp.$$.json config.json
      - name: Push version
        run: |
          cd youtube-dl
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add config.json
          git commit -m "New version"
          git push
